version: "3.7"
services:
  iotweb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_GRAPHQL_API_URI=${GRAPHQL_API_URI}
